# Assignment 2

**Task 1: Lists and Tuples**
1. Create a list of integers from 1 to 100. Slice the list to get every 5th element and print it.
2. Convert the list to a tuple and print the first and last elements.
3. Create a nested list comprehension to generate a 3x3 matrix with values from 1 to 9.

In [1]:
num_list = [i for i in range(1, 101)]
print(num_list[::5])

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]

In [2]:
num_tuple = tuple(num_list)
print("First element:", num_tuple[0])
print("Last element:", num_tuple[-1])

First element: 1
Last element: 100

In [3]:
matrix = [[(3*i + j + 1) for j in range(3)] for i in range(3)]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

**Task 2: Dictionaries**
1. Create a dictionary with student names as keys and their scores as values. The dictionary
should have at least 5 entries.
2. Calculate the average score and print it.
3. Find and print the student(s) with the highest score.

In [4]:
students_dct = {}
students_dct['Swarnotaj'] = 92
students_dct['Ritesh'] = 82
students_dct['Arijit'] = 85
students_dct['Vinayak'] = 77
students_dct['Ngicheng'] = 80
print(students_dct)

{'Swarnotaj': 92, 'Ritesh': 82, 'Arijit': 85, 'Vinayak': 77, 'Ngicheng': 80}

In [ ]:
avg_score = 0

# accumulate sum from values
for score in students_dct.values():
    avg_score += score

# divide by the no. of students
avg_score /= len(students_dct)
print("Average score:", avg_score)

Average score: 83.2

In [ ]:
# find the maximum key (name) based on its value (score) 
top_scorer = max(students_dct, key = lambda s: students_dct[s])
print("Highest scorer:", top_scorer)

Highest scorer: Swarnotaj

**Task 3: NumPy Arrays**
1. Import the NumPy library.
2. Create a 4x4 matrix with random integers between 1 and 100.
3. Create a 4x4 identity matrix and add it to the random matrix. Print the resulting matrix.

In [7]:
import numpy as np

In [8]:
random_matrix = np.random.randint(1, 100, 16).reshape(4, 4)
print(random_matrix)

[[34 93 92 50]
 [72 83 67 55]
 [23 63 49 70]
 [67 17 85  7]]

In [9]:
identity_matrix = np.identity(4, int)
result_matrix = random_matrix + identity_matrix
print(result_matrix)

[[35 93 92 50]
 [72 84 67 55]
 [23 63 50 70]
 [67 17 85  8]]

**Task 4: Array Slicing and Indexing**
1. Slice the matrix to get the second and third rows and columns, and print the submatrix.
2. Replace all even numbers in the matrix with -1 and print the updated matrix.

In [10]:
print(result_matrix[2:4, 2:4])

[[50 70]
 [85  8]]

In [11]:
result_matrix[result_matrix % 2 == 0] = -1
print(result_matrix)

[[35 93 -1 -1]
 [-1 -1 67 55]
 [23 63 -1 -1]
 [67 17 85 -1]]

**Task 5: Broadcasting and Vectorized Operations**
1. Create two 1D arrays, one with 10 random integers and another with integers from 10 to 1.
2. Perform element-wise addition, subtraction, multiplication, and division on the arrays and
print the results.
3. Use broadcasting to add a 1D array to each row of a 2D array and print the result.

In [12]:
arr1 = np.random.randint(1, 10, 10)
arr2 = np.arange(10, 0, -1)
print("Random array:", arr1)
print("Decreasing array:", arr2)

Random array: [4 2 6 5 5 6 3 5 8 7]
Decreasing array: [10  9  8  7  6  5  4  3  2  1]

In [13]:
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", np.round(arr1 / arr2, 3))

Addition: [14 11 14 12 11 11  7  8 10  8]
Subtraction: [-6 -7 -2 -2 -1  1 -1  2  6  6]
Multiplication: [40 18 48 35 30 30 12 15 16  7]
Division: [0.4   0.222 0.75  0.714 0.833 1.2   0.75  1.667 4.    7.   ]

In [14]:
matrix = np.arange(10, 100, 10).reshape(3, 3)
print("Matrix:\n", matrix)
array = np.arange(5, 16, 5)
print("Array:\n", array)
# addition by broadcasting
print("Matrix + Array =\n", matrix + array)

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Array:
 [ 5 10 15]
Matrix + Array =
 [[ 15  30  45]
 [ 45  60  75]
 [ 75  90 105]]

**Task 6: DataFrame Manipulations**
1. Import the Pandas library.
2. Create a DataFrame with columns 'Name', 'Age', 'Department', 'Salary', and 'Years of
Service' with at least 7 entries.
3. Add a new column 'Bonus' which is 10% of the 'Salary' if 'Years of Service' is greater than 5,
otherwise 5%.

In [15]:
import pandas as pd

In [16]:
employees = {
    'Name': ['Arijit', 'Ritesh', 'Mani', 'Naveen', 'Vinayak', 'Swarnotaj', 'Ngicheng'],
    'Age': [28, 35, 42, 30, 26, 27, 38],
    'Department': ['HR', 'Engineering', 'Marketing', 'Finance', 'HR', 'Engineering', 'Marketing'],
    'Salary': [65000, 95000, 80000, 90000, 70000, 105000, 85000],
    'Years of Service': [3, 8, 12, 5, 2, 4, 7]
}
employees_df = pd.DataFrame(employees)
display(employees_df)

        Name  Age   Department  Salary  Years of Service
0     Arijit   28           HR   65000                 3
1     Ritesh   35  Engineering   95000                 8
2       Mani   42    Marketing   80000                12
3     Naveen   30      Finance   90000                 5
4    Vinayak   26           HR   70000                 2
5  Swarnotaj   27  Engineering  105000                 4
6   Ngicheng   38    Marketing   85000                 7

In [ ]:
# Fill the new column using np.where(condition, if value, else value)
employees_df['Bonus'] = np.where(employees_df['Years of Service'] > 5, 0.10, 0.05) * employees_df['Salary']
display(employees_df)

        Name  Age   Department  Salary  Years of Service   Bonus
0     Arijit   28           HR   65000                 3  3250.0
1     Ritesh   35  Engineering   95000                 8  9500.0
2       Mani   42    Marketing   80000                12  8000.0
3     Naveen   30      Finance   90000                 5  4500.0
4    Vinayak   26           HR   70000                 2  3500.0
5  Swarnotaj   27  Engineering  105000                 4  5250.0
6   Ngicheng   38    Marketing   85000                 7  8500.0

**Task 7: Handling Missing Data**
1. Introduce NaN values randomly into the DataFrame.
2. Fill NaN values in 'Salary' with the mean salary and drop rows where 'Department' is NaN.
3. Print the cleaned DataFrame.

In [38]:
import random as rd

employees_df_with_nan = employees_df.copy()
rows, cols = employees_df_with_nan.shape

for i in range(7):
    # generate random address for the matrix (data frame)
    row = rd.randint(0, rows - 1)
    col = rd.randint(1, cols - 1) # exclude name
    employees_df_with_nan.iloc[row, col] = np.nan
    
display(employees_df_with_nan)

        Name   Age   Department    Salary  Years of Service   Bonus
0     Arijit  28.0           HR   65000.0               3.0  3250.0
1     Ritesh   NaN          NaN   95000.0               NaN  9500.0
2       Mani  42.0    Marketing       NaN              12.0  8000.0
3     Naveen  30.0          NaN   90000.0               5.0  4500.0
4    Vinayak  26.0           HR   70000.0               2.0  3500.0
5  Swarnotaj  27.0  Engineering  105000.0               4.0  5250.0
6   Ngicheng  38.0    Marketing   85000.0               NaN     NaN

In [39]:
# replace NaN salaries with avg salary
avg_salary = employees_df_with_nan['Salary'].mean()
employees_df_with_nan['Salary'] = round(employees_df_with_nan['Salary'].fillna(avg_salary), 2)

# drop rows with NaN Department in-place
employees_df_with_nan.dropna(subset=['Department'], inplace=True)

In [45]:
display(employees_df_with_nan)

        Name   Age   Department    Salary  Years of Service   Bonus
0     Arijit  28.0           HR   65000.0               3.0  3250.0
2       Mani  42.0    Marketing   85000.0              12.0  8000.0
4    Vinayak  26.0           HR   70000.0               2.0  3500.0
5  Swarnotaj  27.0  Engineering  105000.0               4.0  5250.0
6   Ngicheng  38.0    Marketing   85000.0               NaN     NaN

**Task 8: Grouping and Aggregation**
1. Group the DataFrame by 'Department' and calculate the average 'Salary' and total 'Years of
Service' for each department.
2. Print the grouped and aggregated data.

In [46]:
aggregate_stats = employees_df.groupby('Department', as_index=False).agg(
    # aggregate value = ('column name', 'attribute')
    Average_Salary = ('Salary', 'mean'),
    Total_Years_of_Service = ('Years of Service', 'sum')
)

In [47]:
display(aggregate_stats)

    Department  Average_Salary  Total_Years_of_Service
0  Engineering        100000.0                      12
1      Finance         90000.0                       5
2           HR         67500.0                       5
3    Marketing         82500.0                      19

------
End of Assignment